# -*- coding: utf-8 -*-
"""audiospeech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThkEwfPHV_UFH52mnNCi6r547UF_QPUz
"""

from google.colab import files
uploaded = files.upload()

import zipfile, os

zip_name = list(uploaded.keys())[0]   # should be Audio_Speech_Actors_01-24.zip
extract_path = "ravdess_speech"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_name, "r") as z:
    z.extractall(extract_path)

print("Extracted to:", extract_path)
print("Top-level:", os.listdir(extract_path)[:10])

import os

wav_count = 0
for root, _, files in os.walk(extract_path):
    for f in files:
        if f.lower().endswith(".wav"):
            wav_count += 1

print("Total WAV files found:", wav_count)

# pip install -U librosa soundfile numpy pandas scikit-learn tqdm

import os
import numpy as np
import pandas as pd
import librosa
from tqdm import tqdm

from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

RAVDESS_ROOT = "ravdess_speech"

EMOTION_MAP = {
    1: "neutral", 2: "calm", 3: "happy", 4: "sad",
    5: "angry", 6: "fearful", 7: "disgust", 8: "surprised",
}

# Stress proxy mapping
STRESS_EMOTIONS = {"angry", "fearful", "sad"}      # label 1
NOSTRESS_EMOTIONS = {"neutral", "calm", "happy"}   # label 0

def parse_ravdess_filename(fname: str):
    base = os.path.splitext(os.path.basename(fname))[0]
    parts = base.split("-")
    if len(parts) != 7:
        return None
    try:
        emotion_code = int(parts[2])
        actor_id = int(parts[6])
    except:
        return None
    emotion = EMOTION_MAP.get(emotion_code)
    if emotion is None:
        return None
    return emotion, actor_id

def extract_features(path: str, sr: int = 16000):
    y, sr = librosa.load(path, sr=sr)
    y, _ = librosa.effects.trim(y, top_db=25)

    if len(y) < sr * 1.0:
        y = np.pad(y, (0, int(sr * 1.0) - len(y)))

    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    mfcc_mean = mfcc.mean(axis=1)
    mfcc_std = mfcc.std(axis=1)

    chroma = librosa.feature.chroma_stft(y=y, sr=sr).mean(axis=1)

    zcr = float(librosa.feature.zero_crossing_rate(y).mean())
    rms = float(librosa.feature.rms(y=y).mean())

    feat = np.hstack([mfcc_mean, mfcc_std, chroma, [zcr, rms]]).astype(np.float32)
    return feat

# Collect wav files
wav_paths = []
for root, _, files in os.walk(RAVDESS_ROOT):
    for f in files:
        if f.lower().endswith(".wav"):
            wav_paths.append(os.path.join(root, f))

print("Total wav files found:", len(wav_paths))

# Build labeled dataframe
rows = []
for p in wav_paths:
    parsed = parse_ravdess_filename(os.path.basename(p))
    if not parsed:
        continue
    emotion, actor = parsed

    if emotion in STRESS_EMOTIONS:
        label = 1
    elif emotion in NOSTRESS_EMOTIONS:
        label = 0
    else:
        continue  # drop disgust/surprised

    rows.append({"path": p, "emotion": emotion, "label": label, "actor": actor})

df = pd.DataFrame(rows)
print("Usable samples:", df.shape)
print("\nLabel distribution:\n", df["label"].value_counts())
print("\nEmotion distribution:\n", df["emotion"].value_counts())

# Extract features
X_list, y_list, g_list = [], [], []
for _, r in tqdm(df.iterrows(), total=len(df)):
    X_list.append(extract_features(r["path"]))
    y_list.append(int(r["label"]))
    g_list.append(int(r["actor"]))

X = np.vstack(X_list)
y = np.array(y_list, dtype=int)
groups = np.array(g_list, dtype=int)

# Actor-independent split
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", C=3.0, gamma="scale", probability=True, class_weight="balanced", random_state=42))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, digits=4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))

from pprint import pprint

for i, r in df.head(20).iterrows():
    print(i, r["emotion"], r["path"])

idx = 5  # change this
audio_path = df.loc[idx, "path"]

def stress_level(prob):
    if prob < 0.40:
        return "Low"
    elif prob < 0.70:
        return "Moderate"
    else:
        return "High"

def predict_stress_from_audio(audio_path: str):
    feat = extract_features(audio_path)
    prob = float(model.predict_proba(feat.reshape(1, -1))[0, 1])
    return {
        "file": os.path.basename(audio_path),
        "stress_probability": round(prob, 4),
        "stress_level": stress_level(prob)
    }

pprint(predict_stress_from_audio(audio_path))

for i, row in df.head(150).iterrows():
    print(i, row["emotion"], row["path"])

from pprint import pprint

idx = int(input("Enter the index number of the file you want: "))

audio_path = df.loc[idx, "path"]

print("Selected file:", audio_path)
pprint(predict_stress_from_audio(audio_path))

