# -*- coding: utf-8 -*-
"""audiosong.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5KGPwXjiolxf18Np8nDush4sGV1PCCI
"""

from google.colab import files

print("Upload your extracted RAVDESS folder as a ZIP file")
uploaded = files.upload()

import zipfile
import os

zip_path = "Audio_Song_Actors_01-24.zip"
extract_path = "ravdess_data"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete.")
print("Top-level folders:", os.listdir(extract_path))

wav_count = 0
for root, _, files in os.walk(extract_path):
    for f in files:
        if f.lower().endswith(".wav"):
            wav_count += 1

print("Total WAV files found:", wav_count)

import os
import numpy as np
import pandas as pd
import librosa

from tqdm import tqdm

from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

# Extracted folder (you already have this)
RAVDESS_ROOT = "ravdess_data"

# RAVDESS emotion codes
EMOTION_MAP = {
    1: "neutral",
    2: "calm",
    3: "happy",
    4: "sad",
    5: "angry",
    6: "fearful",
    7: "disgust",
    8: "surprised",
}

# Stress proxy mapping (you can tweak later)
STRESS_EMOTIONS = {"angry", "fearful", "sad"}       # label 1
NOSTRESS_EMOTIONS = {"neutral", "calm", "happy"}    # label 0

def parse_ravdess_filename(fname: str):
    """
    Format: 03-02-EMOTION-INTENSITY-STATEMENT-REPETITION-ACTOR.wav  (song=02 in 2nd field)
    We only need emotion code and actor id.
    """
    base = os.path.splitext(os.path.basename(fname))[0]
    parts = base.split("-")
    if len(parts) != 7:
        return None
    try:
        emotion_code = int(parts[2])
        actor_id = int(parts[6])
    except:
        return None
    emotion = EMOTION_MAP.get(emotion_code)
    if emotion is None:
        return None
    return emotion, actor_id

def extract_features(path: str, sr: int = 16000):
    """
    No major shortcuts. Uses MFCC mean/std + chroma + RMS + ZCR.
    """
    y, sr = librosa.load(path, sr=sr)
    y, _ = librosa.effects.trim(y, top_db=25)

    # Handle very short audio
    if len(y) < sr * 1.0:
        y = np.pad(y, (0, int(sr * 1.0) - len(y)))

    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)
    mfcc_mean = mfcc.mean(axis=1)
    mfcc_std = mfcc.std(axis=1)

    chroma = librosa.feature.chroma_stft(y=y, sr=sr).mean(axis=1)

    zcr = float(librosa.feature.zero_crossing_rate(y).mean())
    rms = float(librosa.feature.rms(y=y).mean())

    feat = np.hstack([mfcc_mean, mfcc_std, chroma, [zcr, rms]]).astype(np.float32)
    return feat

wav_paths = []
for root, _, files in os.walk(RAVDESS_ROOT):
    for f in files:
        if f.lower().endswith(".wav"):
            wav_paths.append(os.path.join(root, f))

print("Total wav files found:", len(wav_paths))

rows = []
for p in wav_paths:
    parsed = parse_ravdess_filename(os.path.basename(p))
    if not parsed:
        continue
    emotion, actor = parsed

    if emotion in STRESS_EMOTIONS:
        label = 1
    elif emotion in NOSTRESS_EMOTIONS:
        label = 0
    else:
        continue  # drop disgust/surprised by default

    rows.append({"path": p, "emotion": emotion, "label": label, "actor": actor})

df = pd.DataFrame(rows)
print("Usable samples:", df.shape)
print("\nLabel distribution:\n", df["label"].value_counts())
print("\nEmotion distribution:\n", df["emotion"].value_counts())
df.head()

X_list, y_list, g_list = [], [], []

for _, r in tqdm(df.iterrows(), total=len(df)):
    X_list.append(extract_features(r["path"]))
    y_list.append(int(r["label"]))
    g_list.append(int(r["actor"]))

X = np.vstack(X_list)
y = np.array(y_list, dtype=int)
groups = np.array(g_list, dtype=int)

print("X shape:", X.shape, "y shape:", y.shape)

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("Train size:", X_train.shape, "Test size:", X_test.shape)
print("Train labels:", np.bincount(y_train), "Test labels:", np.bincount(y_test))

model = Pipeline([
    ("scaler", StandardScaler()),
    ("svm", SVC(kernel="rbf", C=3.0, gamma="scale", probability=True, class_weight="balanced", random_state=42))
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, digits=4))
print("ROC-AUC:", round(roc_auc_score(y_test, y_prob), 4))

def stress_level(prob):
    if prob < 0.40:
        return "Low"
    elif prob < 0.70:
        return "Moderate"
    else:
        return "High"

def predict_stress_from_audio(audio_path: str):
    feat = extract_features(audio_path)
    prob = float(model.predict_proba(feat.reshape(1, -1))[0, 1])  # P(stress=1)
    pred = int(prob >= 0.5)
    return {
        "file": os.path.basename(audio_path),
        "predicted_label": pred,
        "stress_probability": round(prob, 4),
        "stress_level": stress_level(prob)
    }

# Example: test first file in df
print(predict_stress_from_audio(df.iloc[0]["path"]))

import random
from pprint import pprint

# Pick a random file from the dataframe you already built
row = df.sample(1, random_state=random.randint(0, 10_000)).iloc[0]
audio_path = row["path"]

pprint({
    "chosen_file": audio_path,
    "true_emotion": row["emotion"],
    "true_proxy_label": row["label"]  # 1=stress proxy, 0=no-stress proxy
})

pprint(predict_stress_from_audio(audio_path))

for i, p in enumerate(df["path"].head(20)):
    print(i, p)

# Show first 20 files
for i, row in df.head(20).iterrows():
    print(i, row["emotion"], row["path"])

from pprint import pprint

row = df.loc[9]
pprint({
    "emotion": row["emotion"],
    "proxy_label": row["label"]
})

pprint(predict_stress_from_audio(row["path"]))

